// src/Autoflow.Portal.WebPages/src/lib/components/FirstColumn.svelte
<!-- MainComponent.svelte -->
<script lang="ts">
	import '$lib/app.css';
	import { onMount } from 'svelte';
	import NewMessageModal from './NewMessageModal.svelte';
	import type { User } from '$lib/types/interfaces';
	import { setAuthState } from '$lib/stores/authStore';
	import type { UUID } from 'crypto';
	import { usersStore } from '$lib/stores/userStore';
	export let senderUserId: UUID | undefined;
	export let selectedReceiver: User | null;
	export let receivers: User[];
	export let handleSendMessage;

	let users: User[] = [];
	usersStore.users.subscribe((maps: User[]) => {
		users = maps;
	});

	$: {
		console.log('PROPS receiver', receivers);
	}

	let showNewMessageModal = false;
	let searchQuery = '';

	function openNewMessageModal() {
		showNewMessageModal = true;
	}

	function closeNewMessageModal() {
		showNewMessageModal = false;
	}

	$: searchResults = receivers.filter((user) =>
		user.username.toLowerCase().includes(searchQuery.toLowerCase())
	);
	$: {
		console.log('Check searchResults', searchResults);
	}

	const logout = () => {
		localStorage.removeItem('jwtToken');
    	localStorage.removeItem('user');
		setAuthState(false, null);
	};

	// Filter user that is not the sender and not alreay sent message
	$: filteredReceivers = users.filter(
		(user) => user.id !== senderUserId && !receivers.some((receiver) => receiver.id === user.id)
	);
	$: {
		console.log('Check filteredReceivers', filteredReceivers);
	}

	onMount(() => {
		usersStore.fetchUsers();
	});

	async function deleteAccount() {
		// await usersStore.deleteUser(senderUserId);
		logout();
	}
</script>

<main class="w-1/4 border-r border-gray-200 p-4 overflow-auto">
	<!-- Button to open modal -->
	<button on:click={openNewMessageModal} class="bg-blue-500 text-white px-4 py-2 rounded mb-4">
		Send Message to New User
	</button>

	<button on:click={logout} class="bg-red-500 text-white px-4 py-2 rounded mb-4 ml-4">
		Logout
	</button>

	<button on:click={deleteAccount} class="bg-red-500 text-white px-4 py-2 rounded mb-4 ml-4">
		Delete Account
	</button>

	<!-- Search Button -->
	<div class="mb-4">
		<input
			bind:value={searchQuery}
			placeholder="Search receiver..."
			class="w-full px-4 py-2 border border-gray-400 rounded"
		/>
	</div>

	<!-- Search Results / Past Receivers List -->
	<div class="overflow-auto">
		{#if searchResults.length > 0}
			<ul class="flex flex-col w-fit items-start">
				{#each searchResults as result (result.id)}
					<button on:click={() => (selectedReceiver = result)} class="mb-2 cursor-pointer">
						{result.username}
					</button>
				{/each}
			</ul>
		{:else}
			<h3 class="font-bold mb-2">No results</h3>
		{/if}
	</div>
</main>

{#if showNewMessageModal}
	<NewMessageModal
		{senderUserId}
		{filteredReceivers}
		{closeNewMessageModal}
		{handleSendMessage}
		bind:selectedReceiver
	/>
{/if}

// src/Autoflow.Portal.WebPages/src/components/FirstColumnComponent.vue
<template>
  <div class="w-1/4 border-r border-gray-200 p-4 overflow-auto">
    <!-- Button to open modal -->
    <button @click="openNewMessageModal" class="bg-blue-500 text-white px-4 py-2 rounded mb-4">
      Send Message to New User
    </button>

    <button @click="logout" class="bg-red-500 text-white px-4 py-2 rounded mb-4 ml-4">
      Logout
    </button>

    <!-- Search Button -->
    <div class="mb-4">
      <input
        v-model="searchQuery"
        @input="searchReceiver"
        placeholder="Search receiver..."
        class="w-full px-4 py-2 border border-gray-400 rounded"
      />
    </div>

    <!-- Search Results / Past Receivers List -->
    <div class="overflow-auto">
      <div v-if="searchResults.length > 0">
        <ul>
          <li
            v-for="result in searchResults"
            :key="result.userId"
            @click="selectReceiver(result)"
            class="mb-2 cursor-pointer"
          >
            {{ result.username }}
          </li>
        </ul>
      </div>
      <div v-else>
        <h3 class="font-bold mb-2">No results</h3>
      </div>
    </div>
  </div>

  <!-- Modal for sending a message to a new user -->
  <NewMessageModal
    v-if="showNewMessageModal"
    :pastReceivers="firstColumnData"
    @close="showNewMessageModal = false"
    @send="props.firstColumnData.sendMessage"
  />
</template>

<script setup lang="ts">
import { ref, toRefs, type Ref } from 'vue'
import NewMessageModal from '@/components/MessageModalComponent.vue'
import type { FirstColumnData, User } from '@/types/interfaces'
import { useAuthStore } from '@/stores/auth';

const authStore = useAuthStore()
console.log('AuthStore: ', authStore.isLogin, authStore.currentUser)
const props = defineProps<{
  firstColumnData: FirstColumnData
}>()

console.log('FirstColumnData: ', props.firstColumnData)

const showNewMessageModal = ref(false)

const openNewMessageModal = () => {
  showNewMessageModal.value = true
}

const searchQuery = ref('')

const stateProps = ref(props.firstColumnData.receiverUsers)
const searchResults = ref(props.firstColumnData.receiverUsers)

const searchReceiver = () => {
  searchResults.value = stateProps.value.filter((user) =>
    user.username.toLowerCase().includes(searchQuery.value.toLowerCase())
  )
}

const selectReceiver = (receiver: User) => {
  props.firstColumnData.selectedReceiver.value = receiver
}

const logout = () => {
  authStore.logout()
}
</script>
